import { sql } from "drizzle-orm"
import {
	customType,
	index,
	integer,
	jsonb,
	pgTable,
	real,
	text,
	timestamp,
	uniqueIndex,
	vector,
} from "drizzle-orm/pg-core"

export const EMBED_DIM = 1536

/**
 * float4[] fallback exposed as `Float32Array` for cases where pgvector
 * is unavailable at query time. The primary column stays `vector`.
 */
export const float4Array = customType<{ data: number[]; driverData: string }>({
	dataType() {
		return "real[]"
	},
})

/**
 * Read-only handle onto the `text_tsv` generated column (added by
 * migration 0002, `GENERATED ALWAYS AS (to_tsvector('simple', text))
 * STORED`). Postgres computes and maintains it — the app never writes it,
 * so this type only needs to be selectable/filterable, not insertable.
 */
export const tsvectorType = customType<{ data: unknown }>({
	dataType() {
		return "tsvector"
	},
})

export const tenants = pgTable("tenants", {
	id: text("id").primaryKey(),
	name: text("name").notNull(),
	createdAt: timestamp("created_at", { withTimezone: true })
		.notNull()
		.defaultNow(),
})

export const apiKeys = pgTable(
	"api_keys",
	{
		id: text("id").primaryKey(),
		tenantId: text("tenant_id")
			.notNull()
			.references(() => tenants.id, { onDelete: "cascade" }),
		hashedKey: text("hashed_key").notNull(),
		label: text("label"),
		createdAt: timestamp("created_at", { withTimezone: true })
			.notNull()
			.defaultNow(),
		revokedAt: timestamp("revoked_at", { withTimezone: true }),
	},
	(t) => ({
		hashedKeyIdx: uniqueIndex("api_keys_hashed_key_idx").on(t.hashedKey),
		tenantIdx: index("api_keys_tenant_idx").on(t.tenantId),
	}),
)

export const sessions = pgTable(
	"sessions",
	{
		id: text("id").primaryKey(),
		tenantId: text("tenant_id")
			.notNull()
			.references(() => tenants.id, { onDelete: "cascade" }),
		userId: text("user_id"),
		createdAt: timestamp("created_at", { withTimezone: true })
			.notNull()
			.defaultNow(),
		lastSeenAt: timestamp("last_seen_at", { withTimezone: true })
			.notNull()
			.defaultNow(),
	},
	(t) => ({
		tenantIdx: index("sessions_tenant_idx").on(t.tenantId),
	}),
)

export const memories = pgTable(
	"memories",
	{
		id: text("id").primaryKey(),
		tenantId: text("tenant_id")
			.notNull()
			.references(() => tenants.id, { onDelete: "cascade" }),
		userId: text("user_id"),
		sessionId: text("session_id"),
		text: text("text").notNull(),
		kind: text("kind", { enum: ["fact", "preference", "event", "entity"] })
			.notNull()
			.default("fact"),
		source: text("source", { enum: ["text", "voice"] })
			.notNull()
			.default("text"),
		embedding: vector("embedding", { dimensions: EMBED_DIM }),
		metadata: jsonb("metadata").notNull().default(sql`'{}'::jsonb`),
		createdAt: timestamp("created_at", { withTimezone: true })
			.notNull()
			.defaultNow(),
		updatedAt: timestamp("updated_at", { withTimezone: true })
			.notNull()
			.defaultNow(),

		// Bi-temporal validity. validUntil = NULL means "still current". A
		// correction closes out the prior row (validUntil = now()) and
		// links the new one via supersedesId, in one transaction — see
		// core.ts save()'s `revises` path.
		validFrom: timestamp("valid_from", { withTimezone: true })
			.notNull()
			.defaultNow(),
		validUntil: timestamp("valid_until", { withTimezone: true }),
		supersedesId: text("supersedes_id"),

		// Beta-Binomial belief: confidence = alpha / (alpha + beta). Starts
		// at Beta(1,1) — a uniform, neutral prior — and is updated by
		// packages/core/src/belief.ts as corroborating/contradicting
		// evidence arrives across sessions.
		confidenceAlpha: real("confidence_alpha").notNull().default(1),
		confidenceBeta: real("confidence_beta").notNull().default(1),

		// Recency x frequency decay inputs for the temporal RRF channel.
		accessCount: integer("access_count").notNull().default(0),
		lastAccessedAt: timestamp("last_accessed_at", { withTimezone: true }),

		// Generated by Postgres (migration 0002) — see tsvectorType above.
		textTsv: tsvectorType("text_tsv"),
	},
	(t) => ({
		tenantIdx: index("memories_tenant_idx").on(t.tenantId),
		sessionIdx: index("memories_session_idx").on(t.sessionId),
		userIdx: index("memories_user_idx").on(t.userId),
		embedHnsw: index("memories_embedding_hnsw")
			.using("hnsw", t.embedding.op("vector_cosine_ops"))
			.with({ m: 16, ef_construction: 64 }),
		currentIdx: index("memories_tenant_user_current_idx")
			.on(t.tenantId, t.userId, t.validUntil)
			.where(sql`valid_until IS NULL`),
	}),
)

export const entities = pgTable(
	"entities",
	{
		id: text("id").primaryKey(),
		tenantId: text("tenant_id")
			.notNull()
			.references(() => tenants.id, { onDelete: "cascade" }),
		name: text("name").notNull(),
		kind: text("kind").notNull(),
		metadata: jsonb("metadata").notNull().default(sql`'{}'::jsonb`),
		createdAt: timestamp("created_at", { withTimezone: true })
			.notNull()
			.defaultNow(),
	},
	(t) => ({
		tenantNameIdx: index("entities_tenant_name_idx").on(t.tenantId, t.name),
		nameTrgmIdx: index("entities_name_trgm_idx")
			.using("gin", sql`${t.name} gin_trgm_ops`),
	}),
)

export const modelRegistry = pgTable(
	"model_registry",
	{
		id: text("id").primaryKey(),
		tenantId: text("tenant_id").references(() => tenants.id, {
			onDelete: "cascade",
		}),
		role: text("role", { enum: ["embedder", "reranker"] }).notNull(),
		name: text("name").notNull(),
		provider: text("provider").notNull(),
		config: jsonb("config").notNull().default(sql`'{}'::jsonb`),
		createdAt: timestamp("created_at", { withTimezone: true })
			.notNull()
			.defaultNow(),
		activatedAt: timestamp("activated_at", { withTimezone: true }),
	},
	(t) => ({
		tenantRoleIdx: index("model_registry_tenant_role_idx").on(
			t.tenantId,
			t.role,
		),
	}),
)

export const profiles = pgTable(
	"profiles",
	{
		id: text("id").primaryKey(),
		tenantId: text("tenant_id")
			.notNull()
			.references(() => tenants.id, { onDelete: "cascade" }),
		userId: text("user_id").notNull(),
		summary: text("summary").notNull(),
		sourceMemoryIds: jsonb("source_memory_ids").notNull().default(sql`'[]'::jsonb`),
		confidenceAlpha: real("confidence_alpha").notNull().default(1),
		confidenceBeta: real("confidence_beta").notNull().default(1),
		updatedAt: timestamp("updated_at", { withTimezone: true })
			.notNull()
			.defaultNow(),
	},
	(t) => ({
		tenantUserIdx: uniqueIndex("profiles_tenant_user_idx").on(
			t.tenantId,
			t.userId,
		),
	}),
)

export const relations = pgTable(
	"relations",
	{
		id: text("id").primaryKey(),
		tenantId: text("tenant_id")
			.notNull()
			.references(() => tenants.id, { onDelete: "cascade" }),
		fromEntityId: text("from_entity_id")
			.notNull()
			.references(() => entities.id, { onDelete: "cascade" }),
		toEntityId: text("to_entity_id")
			.notNull()
			.references(() => entities.id, { onDelete: "cascade" }),
		predicate: text("predicate").notNull(),
		memoryId: text("memory_id").references(() => memories.id, {
			onDelete: "set null",
		}),
		createdAt: timestamp("created_at", { withTimezone: true })
			.notNull()
			.defaultNow(),
	},
	(t) => ({
		tenantIdx: index("relations_tenant_idx").on(t.tenantId),
		fromIdx: index("relations_from_idx").on(t.fromEntityId),
	}),
)
